_G.Loader = require('core.loader')
_G.Log = require('core.logs')
_G.Checker = require('core.checker')
_G.CMD = require('core.cmd')
_G.KM = require('core.keymapping')

Loader('settings.options')
Loader('settings.keymaps')
Loader('commands.init')
Loader('plugins.init')
