-- Run: nvim --headless -i NONE '+luafile ~/.public-dotfiles/nvim/tests/health-fixes.lua' +qa
vim.v.errmsg = ''
local conform = require('conform')
assert(vim.deep_equal(conform.formatters_by_ft.nix, { 'alejandra' }))
local buf = vim.api.nvim_create_buf(false, true)
vim.bo[buf].filetype = 'nix'
vim.api.nvim_buf_set_lines(buf, 0, -1, false, { '{foo=1;}' })
conform.format({ bufnr = buf, async = false, timeout_ms = 5000 }, function(err)
  assert(not err, tostring(err))
end)
assert(table.concat(vim.api.nvim_buf_get_lines(buf, 0, -1, false), '\n'):find('foo = 1;', 1, true))
vim.api.nvim_buf_delete(buf, { force = true })
vim.notify('Health fixes check', vim.log.levels.INFO)
assert(vim.notify == Snacks.notifier.notify, 'Snacks must handle notifications')
Snacks.notifier.show_history()
assert(vim.tbl_contains(require('mason-lspconfig.settings').current.automatic_enable.exclude, 'efm'))
assert(not vim.lsp.is_enabled('efm'))
assert(vim.filetype.match({ filename = '/etc/nginx/sites-enabled/example' }) == 'nginx')
assert(vim.filetype.match({ filename = '/etc/nginx/sites-available/example' }) == 'nginx')
assert(vim.filetype.match({ filename = '/tmp/example.tofu' }) == 'opentofu')
assert(vim.treesitter.language.get_lang('yaml.docker-compose') == 'yaml')
assert(vim.v.errmsg == '', vim.v.errmsg)
assert(vim.treesitter.language.get_lang('jsonc') == 'json')
print('Health fixes: OK')
