logo_type = "custom"
custom_logo_path = "~/.config/dott/logo.txt"

[structure]
position = "left"

[[structure.build]]
module = "logo"

[[structure.build]]
module = "entries"

[[structure.build]]
module = "colors"

[[structure.build]]
module = "clock"

[[structure.build]]
module = "selected"

[[structure.build]]
module = "help"


[[entries]]
name = "Developer Session"
command = "tmux"
args = ["new", "-A", "-s", "develop"]

[[entries]]
name = "Monitor Session"
command = "tmux"
args = ["new", "-A", "-s", "monitor"]

[[entries]]
name = "View Dotfiles"
command = "ll"
args = ["~/.config"]

[[entries]]
name = "Edit Neovim Config"
command = "nvim"
args = ["~/.config/nvim/"]

[[entries]]
name = "Edit Shell Config"
command = "nvim"
args = ["~/.zshrc"]

[[entries]]
name = "System Monitor"
command = "htop"
args = []

[[entries]]
name = "Configure Dott"
command = "nvim"
args = ["~/.config/dott/config.toml"]

[[entries]]
name = "Quit"
command = ""
args = []

[custom]

[custom.terminal_colors]
shape = "squares"

[custom.clock]

[custom.selected]

[custom.break]
lines = 2
