# ─────────────────────────────────────────────────────────────────────────────
# Reglas de ventanas
# ─────────────────────────────────────────────────────────────────────────────

# Suprimir maximize en todas las ventanas — el layout master lo gestiona
windowrulev2 = suppressevent maximize, class:.*

# ── Ventanas flotantes ────────────────────────────────────────────────────────
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, title:^(Picture-in-Picture)$
